ProjetoIntegrador/src/main/java/br/pucpr/bsi/projetoIntegrador/nomeProjeto/view/mb/ManterArtistaMB.java
package br.pucpr.bsi.projetoIntegrador.nomeProjeto.view.mb;

import static br.pucpr.bsi.projetoIntegrador.nomeProjeto.view.mb.PesquisarArtistaMB.ARTISTA_SELECIONADA;
import static br.pucpr.bsi.projetoIntegrador.nomeProjeto.view.mb.PesquisarArtistaMB.FILTRO_PESQUISA;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.log4j.Logger;

import br.pucpr.bsi.projetoIntegrador.nomeProjeto.bc.ArtistaBC;
import br.pucpr.bsi.projetoIntegrador.nomeProjeto.exception.BSIException;
import br.pucpr.bsi.projetoIntegrador.nomeProjeto.model.Artista;
import br.pucpr.bsi.projetoIntegrador.nomeProjeto.view.mb.utils.ViewUtil;
import br.pucpr.bsi.projetoIntegrador.nomeProjeto.view.messages.MessagesUtils;

/**
 * @author Everson Mauda
 * @version 1.0.0
 */

@ManagedBean
@ViewScoped
public class ManterArtistaMB implements Serializable{
	
	public enum Acoes {
		EDITAR, EXCLUIR, INCLUIR, VISUALIZAR;
	}
	
	/////////////////////////////////////
	// Atributos
	/////////////////////////////////////
	
	private static final long serialVersionUID = 1L;
	
	//Utilizado para logs via Log4J
	private static Logger log = Logger.getLogger(ManterArtistaMB.class);
	
	private Artista artista = new Artista();
	private Artista filtroPesquisa;
	
	private Acoes acao = Acoes.INCLUIR;
	
	/////////////////////////////////////
	// Construtores
	/////////////////////////////////////
	
	public ManterArtistaMB() {
	}
	
	@PostConstruct
	private void init(){
		acao = (Acoes) ViewUtil.getParameter(Acoes.class);
		if(acao != null && !Acoes.INCLUIR.equals(acao)){
			artista = (Artista) ViewUtil.getParameter(ARTISTA_SELECIONADA);
			if(artista == null){
				throw new BSIException("ER0052");
			}
			log.debug("Valor do Artista:" + artista);
			filtroPesquisa = (Artista) ViewUtil.getParameter(FILTRO_PESQUISA);
			log.debug("Valor do Filtro:" + filtroPesquisa);
		} else  {
			acao = Acoes.INCLUIR;
		}
	}	
	
	/////////////////////////////////////
	// Actions
	/////////////////////////////////////
	
	
	//Action de Salvar Usuario
	public String salvar() {
		if(isAcaoIncluir()){
			ArtistaBC.getInstance().insert(this.artista);
		} else if(isAcaoEditar()){
			ArtistaBC.getInstance().update(this.artista);
		} else if(isAcaoExcluir()){
			ArtistaBC.getInstance().delete(this.artista);
		}
		MessagesUtils.addInfo("sucesso", "IN0000");
		return voltar();
	}
	
	public String voltar(){
		ViewUtil.setRequestParameter(FILTRO_PESQUISA, filtroPesquisa);
		return "pesquisarArtista";
	}
	
	//Action para reset do cadastro
	public void limpar() {
		artista = new Artista();
	}
	
	/////////////////////////////////////
	// Metodos Utilitarios
	/////////////////////////////////////
	
	public boolean isAcaoEditar(){
		return Acoes.EDITAR.equals(acao);
	}
	
	public boolean isAcaoExcluir(){
		return Acoes.EXCLUIR.equals(acao);
	}	
	
	public boolean isAcaoIncluir(){
		return Acoes.INCLUIR.equals(acao);
	}

	public boolean isAcaoVisualizar(){
		return Acoes.VISUALIZAR.equals(acao);
	}
	
	/////////////////////////////////////
	// Getters and Setters
	/////////////////////////////////////
	
	public Artista getArtista() {
		return artista;
	}
	
	public void setAviao(Artista aviao) {
		this.artista = aviao;
	}
	
	public void setAcao(Acoes acao) {
		this.acao = acao;
	}
	
	public String getTitle(){
		switch(acao){
			case EDITAR:
				return MessagesUtils.getLabel("editarArtista");
			case EXCLUIR:
				return MessagesUtils.getLabel("excluirArtista");
			case INCLUIR:
				return MessagesUtils.getLabel("incluirArtista");
			case VISUALIZAR:
				return MessagesUtils.getLabel("visualizarArtista");
		}
		return null;
	}
}

ProjetoIntegrador/src/main/webapp/paginas/manterArtista.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="centerContent">
		<h:form>
			<p:panel>
				<f:facet name="header">
					<h1>
						<h:outputText value="#{manterArtistaMB.title}" />
					</h1>
				</f:facet>
				<p:panelGrid columns="2" columnClasses="labelField, textField">
					<h:outputLabel for="codigo" value="#{msg['nome']}:" />
					<p:inputText id="codigo" value="#{manterArtistaMB.artista.nome}"
						disabled="#{manterArtistaMB.acaoVisualizar}" />
				</p:panelGrid>

				<f:facet name="footer">
					<p:panel toggleTitle="#{msg['acoes']}" styleClass="noBorder">
						<p:commandButton id="submit" value="#{msg['salvar']}"
								action="#{manterArtistaMB.salvar}" ajax="false"
								rendered="#{not manterArtistaMB.acaoVisualizar}" />
							
						<p:commandButton id="reset" value="#{msg['voltar']}"
								action="#{manterArtistaMB.voltar}" ajax="false" />
					</p:panel>
				</f:facet>
			</p:panel>
		</h:form>
	</ui:define>
</ui:composition>

ProjetoIntegrador/src/main/webapp/paginas/pesquisarArtista.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="centerContent">
		<h:form>
			<p:panel>
				<f:facet name="header">
					<h1>#{msg['pesquisarArtista']}</h1>
				</f:facet>
				<p:panel toggleable="true" toggleSpeed="500">
						<f:facet name="header">
							#{msg['filtroPesquisa']}
						</f:facet>
					<p:panelGrid columns="4" columnClasses="labelField, textField, labelField, textField">
						<h:outputLabel for="codigo" value="#{msg['nome']}:"/>
						<p:inputText id="codigo" value="#{pesquisarArtistaMB.filtroPesquisa.nome}" />
					</p:panelGrid>
				
					<p:panel styleClass="noBorder">
						<p:commandButton value="#{msg['pesquisar']}"
							action="#{pesquisarArtistaMB.pesquisar}" update="resultados" />
					</p:panel>
				</p:panel>

				<p:spacer height="25px"/>

				<p:panel id="resultados" styleClass="noBorder">
					<p:dataTable value="#{pesquisarArtistaMB.artistas}" var="artista"
							rendered="#{not empty pesquisarArtistaMB.artistas}"
							selectionMode="single"
							selection="#{pesquisarArtistaMB.artistaSelecionada}"
							rowKey="#{artista.id}">
						
						<f:facet name="header">
							#{msg['resultados']}
						</f:facet>

						<p:column headerText="#{msg['nome']}">
							#{artista.nome}
						</p:column>

						<f:facet name="footer">
							<p:commandButton value="#{msg['editar']}"
								action="#{pesquisarArtistaMB.editar}" ajax="false" />
							<p:commandButton value="#{msg['excluir']}"
								action="#{pesquisarArtistaMB.excluir}" ajax="false" />
							<p:commandButton value="#{msg['visualizar']}"
								action="#{pesquisarArtistaMB.visualizar}" ajax="false" />
						</f:facet>
					</p:dataTable>
				</p:panel>
			</p:panel>
		</h:form>
	</ui:define>
</ui:composition>